name: Deploy to EC2 (DEV)

on:
 push:
    branches:
      - compras     

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PUBLIC_IP_COMPRAS }}
          username: ${{ secrets.USER_COMPRAS }}
          key: ${{ secrets.VOCKEY_FILE_COMPRAS }}
          script: |
            yum update -y
            yum install -y nodejs npm git
            rm -rf /opt/Compras
            mkdir -p /opt/Compras
            cd /opt/Compras
            git clone https://${{ secrets.GH_TOKEN_COMPRAS }}@github.com/alkemyTech/UMSA-DevOps-T4 .
            npm install express 
            npm install -g pm2
            pm2 start app.js
            pm2 status