name: Deploy to EC2 (DEV)

on:
 push:
    branches:
      - compras     

jobs:
 deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_COMPRAS }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_COMPRAS }}
        username: ec2-user
        key: ${{ secrets.VOCKEY_FILE_COMPRAS }}
        script: |
          sudo yum install -y nodejs npm git
          sudo mkdir -p /opt/Compras
          sudo rm -rf /opt/Compras/* || true
          cd /opt/Compras
          sudo git clone https://${{ secrets.GH_TOKEN_COMPRAS }}@github.com/alkemyTech/UMSA-DevOps-T4.git
          sudo npm install express
          sudo npm install -g pm2
          sudo pm2 start app.js
          sudo pm2 save
          sudo pm2 startup