name: Pagos_Snyk_DEV

on:
   push:
    branches:
      - pagos

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Snyk to check for vulnerabilities
        id: snyk
        continue-on-error: true
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN_pagos }}
        with:
          args: --all-projects --severity-threshold=high --json > snyk_report.json

      - name: Archive vulnerability report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: snyk_report
          path: snyk_report.json
          
      - name: Fail on vulnerability
        if: steps.snyk.outcome == 'failure'
        run: exit 1
