name: remote_ssh_command_ventas_qa

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.QA_PRUEBA_HOST }}
          username: ${{ secrets.USER_VENTAS }}
          key: ${{ secrets.QA_PRUEBA_SSH }}
          script: |
            sudo su  # Cambiar al usuario root
            sudo yum update -y
            sudo yum install -y nodejs npm git
            sudo rm -rf /opt/Ventas_qa
            sudo mkdir -p /opt/Ventas_qa
            sudo cd /opt/Ventas_qa
            sudo git clone https://${{ secrets.GH_TOKEN }}@github.com/alkemyTech/UMSA-DevOps-T4 .
            sudo echo 'FROM node:latest' > Dockerfile
            sudo echo 'WORKDIR /usr/src/app' >> Dockerfile
            sudo echo 'COPY . .' >> Dockerfile
            sudo echo 'RUN npm install' >> Dockerfile
            sudo echo 'EXPOSE 3000' >> Dockerfile
            sudo echo 'CMD ["node", "app.js"]' >> Dockerfile
      
      - name: Build Docker image
        run: |
          cd /opt/Ventas_qa
          docker build -t mi-aplicacion-node .

            
    
